// Power Query (M) - adjust folder path if needed
let
    SourceFolder = "data",
    Orders = Csv.Document(File.Contents(SourceFolder & "/orders.csv"),[Delimiter=",", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    OrdersPromoted = Table.PromoteHeaders(Orders, [PromoteAllScalars=true]),
    OrdersTypes = Table.TransformColumnTypes(OrdersPromoted,{
        {"order_id", type text},{"order_date", type date},{"sku", type text},
        {"category", type text},{"brand", type text},{"region", type text},
        {"units", Int64.Type},{"unit_price", type number},{"discount_pct", type number},
        {"unit_cost", type number},{"returned", Int64.Type},{"sessions", Int64.Type},
        {"product_views", Int64.Type},{"add_to_cart", Int64.Type}
    }),
    Products = Csv.Document(File.Contents(SourceFolder & "/products.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
    ProductsPromoted = Table.PromoteHeaders(Products, [PromoteAllScalars=true]),
    ProductsTypes = Table.TransformColumnTypes(ProductsPromoted,{
        {"sku", type text},{"category", type text},{"brand", type text},
        {"base_price", type number},{"cost_ratio", type number}
    }),
    Calendar = Csv.Document(File.Contents(SourceFolder & "/calendar.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]),
    CalendarPromoted = Table.PromoteHeaders(Calendar, [PromoteAllScalars=true]),
    CalendarTypes = Table.TransformColumnTypes(CalendarPromoted,{
        {"date", type date},{"year", Int64.Type},{"month", Int64.Type},{"day", Int64.Type},
        {"dow", Int64.Type},{"week", Int64.Type},{"is_event", Int64.Type}
    })
in
    OrdersTypes